### Регистрация пользователя
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "testuser7118",
  "password": "password123",
  "email": "test@example.com",
  "firstName": "Test",
  "lastName": "User",
  "phoneNumber": "+123456789"
}

### Аутентификация обычного пользователя
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "testuser2",
  "password": "password123"
}


### Аутентификация администратора
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}



### Создание первого дебетового счета
POST http://localhost:8080/api/debit-cards
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJpYXQiOjE3NjQ5NTMwOTEsImV4cCI6MTc2NDk1NjY5MX0.ovzBzKTtsU7eE9iu3PLoI3oq4CoKEiGxC18TjpoInSo
Content-Type: application/json



### Создание второго дебетового счета
POST http://localhost:8080/api/debit-cards
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJpYXQiOjE3NjM5OTcwNDcsImV4cCI6MTc2NDAwMDY0N30.-Z-N4tgMgFb07zqW8Y-NKSUXtMYL4eWkOgQrx1bitg0
Content-Type: application/json



### Создание кредитного счета
POST http://localhost:8080/api/credit-cards/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJpYXQiOjE3NjQ5NDM5MTAsImV4cCI6MTc2NDk0NzUxMH0.Pq1cSZU6SuYHq0Gm-tu_bzlhnpRkJ-u-W1F0mwLBJDg
Content-Type: application/json




### Пополнение первого счета
POST http://localhost:8080/api/transactions/deposit
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJpYXQiOjE3NjQ5NTMwOTEsImV4cCI6MTc2NDk1NjY5MX0.ovzBzKTtsU7eE9iu3PLoI3oq4CoKEiGxC18TjpoInSo
Content-Type: application/json

{
  "cardNumber": "3029511518",
  "amount": 5000,
  "comment": "Пополнение"
}

### Перевод между счетами
POST http://localhost:8080/api/transactions/transfer
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc2NDAwNzUzNiwiZXhwIjoxNzY0MDExMTM2fQ.cQEfsBopanysz9vaHEajIXgni0anpTu6fnDxsS1imSc
Content-Type: application/json

{
  "fromCard": "0092386887",
  "toCard": "6632163960",
  "amount": 250,
  "comment": "Перевод"
}

### Снятие средств
POST http://localhost:8080/api/transactions/withdraw
Authorization: Bearer yJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJpYXQiOjE3NjQwMDE4MDcsImV4cCI6MTc2NDAwNTQwN30.WceG5tdl0Qp0MkitGgNaW47Lysuhx2SFQ2vBUl8ZJXs
Content-Type: application/json

{
  "cardNumber": "0964374508",
  "amount": 500,
  "comment": "Снятие"
}

###Все транзакции для пользователя
GET http://localhost:8080/api/transactions/getAllForUser
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJpYXQiOjE3NjQ5NTMyMzksImV4cCI6MTc2NDk1NjgzOX0.PCV15kXykP_tZvjgqvqph3yUiRtRphudQkBv_hiPydY




###Все счаета
GET http://localhost:8080/api/cards/getCards
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJpYXQiOjE3NjQ5NDM5MTAsImV4cCI6MTc2NDk0NzUxMH0.Pq1cSZU6SuYHq0Gm-tu_bzlhnpRkJ-u-W1F0mwLBJDg

### Увеличение кредитного лимита (только админ)
PUT http://localhost:8080/api/credit-cards/{{credit_card_number}}/increase-limit?newLimit=6000.00
Authorization: Bearer

### Уменьшение кредитного лимита (только админ)
PUT http://localhost:8080/api/credit-cards/{{credit_card_number}}/decrease-limit?newLimit=5500.00
Authorization: Bearer

### Установка процентной ставки (только админ)
PUT http://localhost:8080/api/credit-cards/{{credit_card_number}}/set-interest?newRate=6.5
Authorization: Bearer

### Удаление кредитного счета (только админ)
DELETE http://localhost:8080/api/credit-cards/{{credit_card_number}}
Authorization: Bearer



### asdasd
POST http://localhost:8080/api/credit-cards/accrue-interest
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2MjcxNDE3MiwiZXhwIjoxNzYyNzE3NzcyfQ.Ukqwwvpya5IXEtoQ5-iiVE0OdZHpyS2hxyLWfsOYT5E

### Все транзакции
GET http://localhost:8080/api/transactions/getAll
Authorization: Bearer yJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2Mjk1MzI5MiwiZXhwIjoxNzYyOTU2ODkyfQ.y1jwpa-GK_aW9N9YDnXCi4YT4zaGtiJ-ezcHtxbssA0





### Получить все уведомления пользователя
GET http://localhost:8080/api/notifications/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJpYXQiOjE3NjQwMDc2NTksImV4cCI6MTc2NDAxMTI1OX0.fq9qP7lsmnXx14RGsglRjSFoM1pDnWs1k3QMHwxJb-Y

### Получить непрочитанные уведомления пользователя
GET http://localhost:8080/api/notifications/unread
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJpYXQiOjE3NjM5OTc0NzAsImV4cCI6MTc2NDAwMTA3MH0.2IL6I-vjlfh8mxNMK386ctLOI0rSdbILOLB9pRGr3JI

